-- ============================================================================
-- 2026-09-11  啵宝（bobo）记忆与日志表补档
-- ----------------------------------------------------------------------------
-- 背景：啵宝的记忆系统（L4 向量长期记忆）与其日志表**只存在于线上数据库**，
--       仓库中没有任何建表脚本。`functions/bobo-reply.ts` 直接依赖它们，
--       一旦线上被重建/迁移就会整体失效且无法复原。
--
-- 本迁移把线上实际结构补写成可版本化的定义（幂等；线上已存在则不改动）。
-- 注意：bobo_memories.embedding 依赖 pgvector 扩展与 HNSW 索引。
--
-- 说明：本文件仅做"补档"，不改变线上已有数据与行为。
-- ============================================================================

-- pgvector（向量相似度检索）
CREATE EXTENSION IF NOT EXISTS vector;

-- ── 配置表（单行，id 恒为 1）──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.bobo_config (
  id                integer PRIMARY KEY,
  enabled           boolean NOT NULL DEFAULT true,
  reply_cooldown_ms integer NOT NULL DEFAULT 1500,
  deep_quiet_start  integer NOT NULL DEFAULT 0,
  deep_quiet_end    integer NOT NULL DEFAULT 6,
  updated_at        timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT bobo_config_id_check CHECK (id = 1)
);

-- ── L4 长期记忆（向量）────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.bobo_memories (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scope           text NOT NULL,
  user_id         uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  channel_id      uuid REFERENCES public.channels(id) ON DELETE CASCADE,
  content         text NOT NULL,
  embedding       vector,
  embedding_model text,
  weight          real NOT NULL DEFAULT 1.0,
  last_seen       timestamptz NOT NULL DEFAULT now(),
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT bobo_memories_scope_check CHECK (scope = ANY (ARRAY['user','channel','global'])),
  -- user scope 必须带 user_id；channel scope 必须带 channel_id；global 两者皆空
  CONSTRAINT bobo_mem_scope_target CHECK (
    (scope = 'user'    AND user_id IS NOT NULL) OR
    (scope = 'channel' AND channel_id IS NOT NULL) OR
    (scope = 'global'  AND user_id IS NULL AND channel_id IS NULL)
  )
);

-- ── 回复/记忆日志（含幂等锁）─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.bobo_reply_log (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trigger_msg_id uuid,
  channel_id     uuid,
  author_id      uuid,
  kind           text NOT NULL,
  ok             boolean NOT NULL DEFAULT true,
  model          text,
  note           text,
  created_at     timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT bobo_reply_log_kind_check CHECK (kind = ANY (ARRAY['reply','weekly','self_comment','memory','claim']))
);

-- ── 索引 ─────────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS bobo_memories_user_idx    ON public.bobo_memories (user_id);
CREATE INDEX IF NOT EXISTS bobo_memories_channel_idx ON public.bobo_memories (channel_id);
CREATE INDEX IF NOT EXISTS bobo_memories_scope_idx   ON public.bobo_memories (scope);
-- 向量近邻检索（余弦距离）
CREATE INDEX IF NOT EXISTS bobo_memories_hnsw_idx
  ON public.bobo_memories USING hnsw (embedding vector_cosine_ops);
CREATE INDEX IF NOT EXISTS bobo_reply_log_created_idx ON public.bobo_reply_log (created_at);
-- 幂等锁：同一触发消息只允许一条 claim 记录（防双回复）
CREATE UNIQUE INDEX IF NOT EXISTS bobo_claim_once_idx
  ON public.bobo_reply_log (trigger_msg_id) WHERE (kind = 'claim' AND trigger_msg_id IS NOT NULL);

-- ── 默认配置行 ───────────────────────────────────────────────────────────────
INSERT INTO public.bobo_config (id, enabled, reply_cooldown_ms, deep_quiet_start, deep_quiet_end)
VALUES (1, true, 1500, 0, 6)
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- 附：本迁移**不包含**啵宝相关函数与触发器（bobo_uid / bobo_claim / bobo_send /
--     bobo_log / bobo_rate_check / bobo_memory_match / bobo_memory_upsert /
--     bobo_memory_decay）的建库脚本 —— 它们同样只存在于线上。
--     备份见 docs/plans/recon/2026-09-11-backup-friend-dm-function-defs.json 的同批导出
--     （如需完整补档，可另开迁移文件）。
-- ============================================================================
